var = {'tracks':
	{
	'href': 'https://api.spotify.com/v1/search?query=Fading+Like+A+Flower+%28Every+Time+You+Leave%29&type=track&offset'
	        '=0&limit=10',
	'items': [
		{'album':
			 {'album_type': 'album', 'artists': [
		{'external_urls':
			 {
				 'spotify': 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY'
			 },
		 'href': 'https://api.spotify.com/v1/artists/2SHhfs4BiDxGQ3oxqf0UHY', 'id': '2SHhfs4BiDxGQ3oxqf0UHY',
		 'name': 'Roxette', 'type': 'artist', 'uri': 'spotify:artist:2SHhfs4BiDxGQ3oxqf0UHY'}],
	                     'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY',
	                                           'CZ', 'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN',
	                                           'HK', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL',
	                                           'NZ', 'NI', 'NO', 'PA', 'PY', 'PE', 'PH', 'PL', 'PT', 'SG', 'SK', 'ES',
	                                           'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB', 'AD', 'LI', 'MC', 'ID', 'JP',
	                                           'TH', 'VN', 'RO', 'IL', 'ZA', 'SA', 'AE', 'BH', 'QA', 'OM', 'KW', 'EG',
	                                           'MA', 'DZ', 'TN', 'LB', 'JO', 'PS', 'IN', 'BY', 'KZ', 'MD', 'UA', 'AL',
	                                           'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE',
	                                           'NG', 'TZ', 'UG', 'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV',
	                                           'CW', 'DM', 'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS',
	                                           'LR', 'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG', 'PR',
	                                           'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL',
	                                           'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM', 'GQ',
	                                           'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ',
	                                           'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ',
	                                           'LY', 'TJ', 'VE', 'ET', 'XK'],
	                     'external_urls':
				  {'spotify': 'https://open.spotify.com/album/5WVNP6IBwMSULc0wehXW8N'
				   },
	                     'href': 'https://api.spotify.com/v1/albums/5WVNP6IBwMSULc0wehXW8N',
	                     'id': '5WVNP6IBwMSULc0wehXW8N', 'images': [
			{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2734f8706e78f75327a99b57607', 'width': 640},
			{'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e024f8706e78f75327a99b57607', 'width': 300},
			{'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048514f8706e78f75327a99b57607', 'width': 64}],
	                     'name': 'Joyride (Extended Version)', 'release_date': '1991-04-02',
	                     'release_date_precision': 'day', 'total_tracks': 18, 'type': 'album',
	                     'uri': 'spotify:album:5WVNP6IBwMSULc0wehXW8N'}, 'artists': [
		{'external_urls': {'spotify': 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY'},
		 'href': 'https://api.spotify.com/v1/artists/2SHhfs4BiDxGQ3oxqf0UHY', 'id': '2SHhfs4BiDxGQ3oxqf0UHY',
		 'name': 'Roxette', 'type': 'artist', 'uri': 'spotify:artist:2SHhfs4BiDxGQ3oxqf0UHY'}],
	           'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DK',
	                                 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU', 'IS', 'IE',
	                                 'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE',
	                                 'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB', 'AD',
	                                 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA', 'AE', 'BH', 'QA', 'OM',
	                                 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS', 'IN', 'BY', 'KZ', 'MD', 'UA', 'AL',
	                                 'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ',
	                                 'UG', 'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM',
	                                 'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM',
	                                 'NA', 'NR', 'NE', 'PW', 'PG', 'PR', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN',
	                                 'LC', 'VC', 'SR', 'TL', 'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD',
	                                 'KM', 'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ',
	                                 'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ',
	                                 'VE', 'ET', 'XK'], 'disc_number': 1, 'duration_ms': 230680, 'explicit': False,
	           'external_ids': {'isrc': 'SEAMA9079030'},
	           'external_urls': {'spotify': 'https://open.spotify.com/track/3r6lBKYbdru7e7ky2MiF75'},
	           'href': 'https://api.spotify.com/v1/tracks/3r6lBKYbdru7e7ky2MiF75', 'id': '3r6lBKYbdru7e7ky2MiF75',
	           'is_local': False, 'name': 'Fading Like A Flower (Every Time You Leave)', 'popularity': 65,
	           'preview_url': 'https://p.scdn.co/mp3-preview/188f3ef774bf14f743972e14b3af83cdd74e4c8c?cid=2c9062fc93e94058be23890e28264258',
	           'track_number': 3, 'type': 'track', 'uri': 'spotify:track:3r6lBKYbdru7e7ky2MiF75'}, {
		          'album': {'album_type': 'compilation', 'artists': [
			          {'external_urls': {'spotify': 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY'},
			           'href': 'https://api.spotify.com/v1/artists/2SHhfs4BiDxGQ3oxqf0UHY',
			           'id': '2SHhfs4BiDxGQ3oxqf0UHY', 'name': 'Roxette', 'type': 'artist',
			           'uri': 'spotify:artist:2SHhfs4BiDxGQ3oxqf0UHY'}],
		                    'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR',
		                                          'CY', 'CZ', 'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR',
		                                          'GT', 'HN', 'HK', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY',
		                                          'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE', 'PH', 'PL',
		                                          'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB',
		                                          'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA',
		                                          'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO',
		                                          'PS', 'IN', 'BY', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK',
		                                          'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG',
		                                          'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM',
		                                          'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR',
		                                          'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG', 'WS',
		                                          'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL',
		                                          'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM',
		                                          'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW',
		                                          'TG', 'UZ', 'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM',
		                                          'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE', 'ET', 'XK'],
		                    'external_urls': {'spotify': 'https://open.spotify.com/album/6Zd1OLqFX5geleqvJ9xtAL'},
		                    'href': 'https://api.spotify.com/v1/albums/6Zd1OLqFX5geleqvJ9xtAL',
		                    'id': '6Zd1OLqFX5geleqvJ9xtAL', 'images': [
				          {'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273ab7b495554c93a381338691c',
				           'width': 640},
				          {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02ab7b495554c93a381338691c',
				           'width': 300},
				          {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851ab7b495554c93a381338691c',
				           'width': 64}], 'name': "Don't Bore Us - Get to the Chorus! Roxette's Greatest Hits",
		                    'release_date': '1995-10-23', 'release_date_precision': 'day', 'total_tracks': 18,
		                    'type': 'album', 'uri': 'spotify:album:6Zd1OLqFX5geleqvJ9xtAL'}, 'artists': [
			{'external_urls': {'spotify': 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY'},
			 'href': 'https://api.spotify.com/v1/artists/2SHhfs4BiDxGQ3oxqf0UHY', 'id': '2SHhfs4BiDxGQ3oxqf0UHY',
			 'name': 'Roxette', 'type': 'artist', 'uri': 'spotify:artist:2SHhfs4BiDxGQ3oxqf0UHY'}],
		          'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ',
		                                'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU',
		                                'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO',
		                                'PA', 'PY', 'PE', 'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR',
		                                'UY', 'US', 'GB', 'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA',
		                                'SA', 'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS',
		                                'IN', 'BY', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR',
		                                'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG', 'AG', 'AM', 'BS', 'BB', 'BZ',
		                                'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT',
		                                'JM', 'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW',
		                                'PG', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL',
		                                'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM', 'GQ', 'SZ',
		                                'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ', 'ZW', 'BJ',
		                                'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE',
		                                'ET', 'XK'], 'disc_number': 1, 'duration_ms': 230680, 'explicit': False,
		          'external_ids': {'isrc': 'SEAMA9079030'},
		          'external_urls': {'spotify': 'https://open.spotify.com/track/7lMGVp49BU4MS0bJq6nFUu'},
		          'href': 'https://api.spotify.com/v1/tracks/7lMGVp49BU4MS0bJq6nFUu', 'id': '7lMGVp49BU4MS0bJq6nFUu',
		          'is_local': False, 'name': 'Fading Like A Flower (Every Time You Leave)', 'popularity': 42,
		          'preview_url': 'https://p.scdn.co/mp3-preview/188f3ef774bf14f743972e14b3af83cdd74e4c8c?cid=2c9062fc93e94058be23890e28264258',
		          'track_number': 9, 'type': 'track', 'uri': 'spotify:track:7lMGVp49BU4MS0bJq6nFUu'}, {
		          'album': {'album_type': 'compilation', 'artists': [
			          {'external_urls': {'spotify': 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY'},
			           'href': 'https://api.spotify.com/v1/artists/2SHhfs4BiDxGQ3oxqf0UHY',
			           'id': '2SHhfs4BiDxGQ3oxqf0UHY', 'name': 'Roxette', 'type': 'artist',
			           'uri': 'spotify:artist:2SHhfs4BiDxGQ3oxqf0UHY'}],
		                    'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CL', 'CO', 'CR', 'CY',
		                                          'CZ', 'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT',
		                                          'HN', 'HK', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY', 'MT',
		                                          'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE', 'PH', 'PL', 'PT',
		                                          'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'GB', 'AD', 'LI',
		                                          'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA', 'AE', 'BH',
		                                          'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS', 'IN',
		                                          'BY', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK', 'RS', 'SI',
		                                          'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG', 'AG', 'AM',
		                                          'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM',
		                                          'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR', 'MW', 'MV',
		                                          'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG', 'WS', 'SM', 'ST',
		                                          'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL', 'TO', 'TT',
		                                          'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM', 'GQ', 'SZ',
		                                          'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ',
		                                          'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG',
		                                          'IQ', 'LY', 'TJ', 'VE', 'ET', 'XK'],
		                    'external_urls': {'spotify': 'https://open.spotify.com/album/1nQK4dpultSS3YeHfYrgEW'},
		                    'href': 'https://api.spotify.com/v1/albums/1nQK4dpultSS3YeHfYrgEW',
		                    'id': '1nQK4dpultSS3YeHfYrgEW', 'images': [
				          {'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273e56f9b5e455ba04fffddc61e',
				           'width': 640},
				          {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02e56f9b5e455ba04fffddc61e',
				           'width': 300},
				          {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851e56f9b5e455ba04fffddc61e',
				           'width': 64}], 'name': 'A Collection of Roxette Hits! Their 20 Greatest Songs!',
		                    'release_date': '2006-10-18', 'release_date_precision': 'day', 'total_tracks': 20,
		                    'type': 'album', 'uri': 'spotify:album:1nQK4dpultSS3YeHfYrgEW'}, 'artists': [
			{'external_urls': {'spotify': 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY'},
			 'href': 'https://api.spotify.com/v1/artists/2SHhfs4BiDxGQ3oxqf0UHY', 'id': '2SHhfs4BiDxGQ3oxqf0UHY',
			 'name': 'Roxette', 'type': 'artist', 'uri': 'spotify:artist:2SHhfs4BiDxGQ3oxqf0UHY'}],
		          'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CL', 'CO', 'CR', 'CY', 'CZ', 'DK',
		                                'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU', 'IS',
		                                'IE', 'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA',
		                                'PY', 'PE', 'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY',
		                                'GB', 'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA', 'AE',
		                                'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS', 'IN', 'BY',
		                                'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR', 'BD', 'PK',
		                                'LK', 'GH', 'KE', 'NG', 'TZ', 'UG', 'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW',
		                                'BF', 'CV', 'CW', 'DM', 'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI',
		                                'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG', 'WS',
		                                'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL', 'TO', 'TT',
		                                'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM', 'GQ', 'SZ', 'GA', 'GN',
		                                'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ', 'ZW', 'BJ', 'MG', 'MU',
		                                'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE', 'ET', 'XK'],
		          'disc_number': 1, 'duration_ms': 230680, 'explicit': False, 'external_ids': {'isrc': 'SEAMA9079030'},
		          'external_urls': {'spotify': 'https://open.spotify.com/track/6Q2dk1L9uCTzYODYaYzO69'},
		          'href': 'https://api.spotify.com/v1/tracks/6Q2dk1L9uCTzYODYaYzO69', 'id': '6Q2dk1L9uCTzYODYaYzO69',
		          'is_local': False, 'name': 'Fading Like A Flower (Every Time You Leave)', 'popularity': 37,
		          'preview_url': 'https://p.scdn.co/mp3-preview/188f3ef774bf14f743972e14b3af83cdd74e4c8c?cid=2c9062fc93e94058be23890e28264258',
		          'track_number': 8, 'type': 'track', 'uri': 'spotify:track:6Q2dk1L9uCTzYODYaYzO69'}, {
		          'album': {'album_type': 'compilation', 'artists': [
			          {'external_urls': {'spotify': 'https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of'},
			           'href': 'https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of',
			           'id': '0LyfQWJT6nXafLPZqxe9Of', 'name': 'Various Artists', 'type': 'artist',
			           'uri': 'spotify:artist:0LyfQWJT6nXafLPZqxe9Of'}], 'available_markets': ['GB', 'IE'],
		                    'external_urls': {'spotify': 'https://open.spotify.com/album/7FQQSKTRD2nMIuO5WQmHaM'},
		                    'href': 'https://api.spotify.com/v1/albums/7FQQSKTRD2nMIuO5WQmHaM',
		                    'id': '7FQQSKTRD2nMIuO5WQmHaM', 'images': [
				          {'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2733e5b9843fa5e4ade6bb67188',
				           'width': 640},
				          {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e023e5b9843fa5e4ade6bb67188',
				           'width': 300},
				          {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048513e5b9843fa5e4ade6bb67188',
				           'width': 64}], 'name': '100% Clubland', 'release_date': '2016-05-06',
		                    'release_date_precision': 'day', 'total_tracks': 80, 'type': 'album',
		                    'uri': 'spotify:album:7FQQSKTRD2nMIuO5WQmHaM'}, 'artists': [
			{'external_urls': {'spotify': 'https://open.spotify.com/artist/3gg8Dn97Im6uNAdafETuNp'},
			 'href': 'https://api.spotify.com/v1/artists/3gg8Dn97Im6uNAdafETuNp', 'id': '3gg8Dn97Im6uNAdafETuNp',
			 'name': 'Dancing DJs', 'type': 'artist', 'uri': 'spotify:artist:3gg8Dn97Im6uNAdafETuNp'}],
		          'available_markets': ['GB', 'IE'], 'disc_number': 1, 'duration_ms': 183032, 'explicit': False,
		          'external_ids': {'isrc': 'GBCFZ1600015'},
		          'external_urls': {'spotify': 'https://open.spotify.com/track/4PbrHOMJLmS6I8nYX37P83'},
		          'href': 'https://api.spotify.com/v1/tracks/4PbrHOMJLmS6I8nYX37P83', 'id': '4PbrHOMJLmS6I8nYX37P83',
		          'is_local': False, 'name': 'Fading Like A Flower', 'popularity': 37, 'preview_url': None,
		          'track_number': 14, 'type': 'track', 'uri': 'spotify:track:4PbrHOMJLmS6I8nYX37P83'}, {
		          'album': {'album_type': 'single', 'artists': [
			          {'external_urls': {'spotify': 'https://open.spotify.com/artist/25Q0qiDzgPP2JghheF8NRM'},
			           'href': 'https://api.spotify.com/v1/artists/25Q0qiDzgPP2JghheF8NRM',
			           'id': '25Q0qiDzgPP2JghheF8NRM', 'name': 'Renauld', 'type': 'artist',
			           'uri': 'spotify:artist:25Q0qiDzgPP2JghheF8NRM'},
			          {'external_urls': {'spotify': 'https://open.spotify.com/artist/2Y6ICKqJ0JCmy0wVp7Il58'},
			           'href': 'https://api.spotify.com/v1/artists/2Y6ICKqJ0JCmy0wVp7Il58',
			           'id': '2Y6ICKqJ0JCmy0wVp7Il58', 'name': 'Mandy Jones', 'type': 'artist',
			           'uri': 'spotify:artist:2Y6ICKqJ0JCmy0wVp7Il58'}],
		                    'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR',
		                                          'CY', 'CZ', 'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR',
		                                          'GT', 'HN', 'HK', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY',
		                                          'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE', 'PH', 'PL',
		                                          'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB',
		                                          'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA',
		                                          'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO',
		                                          'PS', 'IN', 'BY', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK',
		                                          'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG',
		                                          'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM',
		                                          'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR',
		                                          'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG', 'PR',
		                                          'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR',
		                                          'TL', 'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD',
		                                          'KM', 'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP',
		                                          'RW', 'TG', 'UZ', 'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ',
		                                          'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE', 'ET', 'XK'],
		                    'external_urls': {'spotify': 'https://open.spotify.com/album/3IOAQjnxCHDmxRt2gpuTww'},
		                    'href': 'https://api.spotify.com/v1/albums/3IOAQjnxCHDmxRt2gpuTww',
		                    'id': '3IOAQjnxCHDmxRt2gpuTww', 'images': [
				          {'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273d5021c869ef1bf953fd183f3',
				           'width': 640},
				          {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02d5021c869ef1bf953fd183f3',
				           'width': 300},
				          {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851d5021c869ef1bf953fd183f3',
				           'width': 64}], 'name': 'Fading Like a Flower (Every Time You Leave)',
		                    'release_date': '2020-06-12', 'release_date_precision': 'day', 'total_tracks': 1,
		                    'type': 'album', 'uri': 'spotify:album:3IOAQjnxCHDmxRt2gpuTww'}, 'artists': [
			{'external_urls': {'spotify': 'https://open.spotify.com/artist/25Q0qiDzgPP2JghheF8NRM'},
			 'href': 'https://api.spotify.com/v1/artists/25Q0qiDzgPP2JghheF8NRM', 'id': '25Q0qiDzgPP2JghheF8NRM',
			 'name': 'Renauld', 'type': 'artist', 'uri': 'spotify:artist:25Q0qiDzgPP2JghheF8NRM'},
			{'external_urls': {'spotify': 'https://open.spotify.com/artist/2Y6ICKqJ0JCmy0wVp7Il58'},
			 'href': 'https://api.spotify.com/v1/artists/2Y6ICKqJ0JCmy0wVp7Il58', 'id': '2Y6ICKqJ0JCmy0wVp7Il58',
			 'name': 'Mandy Jones', 'type': 'artist', 'uri': 'spotify:artist:2Y6ICKqJ0JCmy0wVp7Il58'}],
		          'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ',
		                                'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU',
		                                'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO',
		                                'PA', 'PY', 'PE', 'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR',
		                                'UY', 'US', 'GB', 'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA',
		                                'SA', 'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS',
		                                'IN', 'BY', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR',
		                                'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG', 'AG', 'AM', 'BS', 'BB', 'BZ',
		                                'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT',
		                                'JM', 'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW',
		                                'PG', 'PR', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR',
		                                'TL', 'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM', 'GQ',
		                                'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ', 'ZW',
		                                'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ',
		                                'VE', 'ET', 'XK'], 'disc_number': 1, 'duration_ms': 176993, 'explicit': False,
		          'external_ids': {'isrc': 'ARF412000125'},
		          'external_urls': {'spotify': 'https://open.spotify.com/track/2dwPVGEtjXWSZhttSNNEyk'},
		          'href': 'https://api.spotify.com/v1/tracks/2dwPVGEtjXWSZhttSNNEyk', 'id': '2dwPVGEtjXWSZhttSNNEyk',
		          'is_local': False, 'name': 'Fading Like a Flower (Every Time You Leave)', 'popularity': 24,
		          'preview_url': 'https://p.scdn.co/mp3-preview/bb1b0a331fb22c80bedde998c1883f898dabc198?cid=2c9062fc93e94058be23890e28264258',
		          'track_number': 1, 'type': 'track', 'uri': 'spotify:track:2dwPVGEtjXWSZhttSNNEyk'}, {
		          'album': {'album_type': 'single', 'artists': [
			          {'external_urls': {'spotify': 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY'},
			           'href': 'https://api.spotify.com/v1/artists/2SHhfs4BiDxGQ3oxqf0UHY',
			           'id': '2SHhfs4BiDxGQ3oxqf0UHY', 'name': 'Roxette', 'type': 'artist',
			           'uri': 'spotify:artist:2SHhfs4BiDxGQ3oxqf0UHY'},
			          {'external_urls': {'spotify': 'https://open.spotify.com/artist/4sTQVOfp9vEMCemLw50sbu'},
			           'href': 'https://api.spotify.com/v1/artists/4sTQVOfp9vEMCemLw50sbu',
			           'id': '4sTQVOfp9vEMCemLw50sbu', 'name': 'Galantis', 'type': 'artist',
			           'uri': 'spotify:artist:4sTQVOfp9vEMCemLw50sbu'}],
		                    'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR',
		                                          'CY', 'CZ', 'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR',
		                                          'GT', 'HN', 'HK', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY',
		                                          'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE', 'PH', 'PL',
		                                          'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB',
		                                          'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA',
		                                          'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO',
		                                          'PS', 'IN', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK', 'RS',
		                                          'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG', 'AG',
		                                          'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ',
		                                          'GM', 'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR', 'MW',
		                                          'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG', 'PR', 'WS',
		                                          'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL',
		                                          'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM',
		                                          'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW',
		                                          'TG', 'UZ', 'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM',
		                                          'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE', 'ET', 'XK'],
		                    'external_urls': {'spotify': 'https://open.spotify.com/album/5wFmirRzEpKhkN1zQR73tT'},
		                    'href': 'https://api.spotify.com/v1/albums/5wFmirRzEpKhkN1zQR73tT',
		                    'id': '5wFmirRzEpKhkN1zQR73tT', 'images': [
				          {'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273c8bad6c2adc223664f162b10',
				           'width': 640},
				          {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02c8bad6c2adc223664f162b10',
				           'width': 300},
				          {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851c8bad6c2adc223664f162b10',
				           'width': 64}], 'name': 'Fading Like A Flower', 'release_date': '2022-04-22',
		                    'release_date_precision': 'day', 'total_tracks': 1, 'type': 'album',
		                    'uri': 'spotify:album:5wFmirRzEpKhkN1zQR73tT'}, 'artists': [
			{'external_urls': {'spotify': 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY'},
			 'href': 'https://api.spotify.com/v1/artists/2SHhfs4BiDxGQ3oxqf0UHY', 'id': '2SHhfs4BiDxGQ3oxqf0UHY',
			 'name': 'Roxette', 'type': 'artist', 'uri': 'spotify:artist:2SHhfs4BiDxGQ3oxqf0UHY'},
			{'external_urls': {'spotify': 'https://open.spotify.com/artist/4sTQVOfp9vEMCemLw50sbu'},
			 'href': 'https://api.spotify.com/v1/artists/4sTQVOfp9vEMCemLw50sbu', 'id': '4sTQVOfp9vEMCemLw50sbu',
			 'name': 'Galantis', 'type': 'artist', 'uri': 'spotify:artist:4sTQVOfp9vEMCemLw50sbu'}],
		          'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ',
		                                'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU',
		                                'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO',
		                                'PA', 'PY', 'PE', 'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR',
		                                'UY', 'US', 'GB', 'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA',
		                                'SA', 'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS',
		                                'IN', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR', 'BD',
		                                'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG', 'AG', 'AM', 'BS', 'BB', 'BZ', 'BT',
		                                'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT', 'JM',
		                                'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG',
		                                'PR', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL',
		                                'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM', 'GQ', 'SZ',
		                                'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ', 'ZW', 'BJ',
		                                'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE',
		                                'ET', 'XK'], 'disc_number': 1, 'duration_ms': 145807, 'explicit': False,
		          'external_ids': {'isrc': 'SEAMA2200001'},
		          'external_urls': {'spotify': 'https://open.spotify.com/track/5THQw2QDTWwOP1Hj543Rb2'},
		          'href': 'https://api.spotify.com/v1/tracks/5THQw2QDTWwOP1Hj543Rb2', 'id': '5THQw2QDTWwOP1Hj543Rb2',
		          'is_local': False, 'name': 'Fading Like A Flower', 'popularity': 52,
		          'preview_url': 'https://p.scdn.co/mp3-preview/af7eae1634028106dabdd5e715307797f20a0c65?cid=2c9062fc93e94058be23890e28264258',
		          'track_number': 1, 'type': 'track', 'uri': 'spotify:track:5THQw2QDTWwOP1Hj543Rb2'}, {
		          'album': {'album_type': 'album', 'artists': [
			          {'external_urls': {'spotify': 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY'},
			           'href': 'https://api.spotify.com/v1/artists/2SHhfs4BiDxGQ3oxqf0UHY',
			           'id': '2SHhfs4BiDxGQ3oxqf0UHY', 'name': 'Roxette', 'type': 'artist',
			           'uri': 'spotify:artist:2SHhfs4BiDxGQ3oxqf0UHY'}],
		                    'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR',
		                                          'CY', 'CZ', 'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR',
		                                          'GT', 'HN', 'HK', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY',
		                                          'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE', 'PH', 'PL',
		                                          'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB',
		                                          'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA',
		                                          'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO',
		                                          'PS', 'IN', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK', 'RS',
		                                          'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG', 'AG',
		                                          'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ',
		                                          'GM', 'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR', 'MW',
		                                          'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG', 'PR', 'WS',
		                                          'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL',
		                                          'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM',
		                                          'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW',
		                                          'TG', 'UZ', 'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM',
		                                          'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE', 'ET', 'XK'],
		                    'external_urls': {'spotify': 'https://open.spotify.com/album/2m4bjcwM03IVCKfiLr3C1f'},
		                    'href': 'https://api.spotify.com/v1/albums/2m4bjcwM03IVCKfiLr3C1f',
		                    'id': '2m4bjcwM03IVCKfiLr3C1f', 'images': [
				          {'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273dd83ef03832861e4aa695eb2',
				           'width': 640},
				          {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02dd83ef03832861e4aa695eb2',
				           'width': 300},
				          {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851dd83ef03832861e4aa695eb2',
				           'width': 64}], 'name': 'ROX RMX Vol. 1 (Remixes From The Roxette Vaults)',
		                    'release_date': '2022-06-24', 'release_date_precision': 'day', 'total_tracks': 14,
		                    'type': 'album', 'uri': 'spotify:album:2m4bjcwM03IVCKfiLr3C1f'}, 'artists': [
			{'external_urls': {'spotify': 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY'},
			 'href': 'https://api.spotify.com/v1/artists/2SHhfs4BiDxGQ3oxqf0UHY', 'id': '2SHhfs4BiDxGQ3oxqf0UHY',
			 'name': 'Roxette', 'type': 'artist', 'uri': 'spotify:artist:2SHhfs4BiDxGQ3oxqf0UHY'},
			{'external_urls': {'spotify': 'https://open.spotify.com/artist/4sTQVOfp9vEMCemLw50sbu'},
			 'href': 'https://api.spotify.com/v1/artists/4sTQVOfp9vEMCemLw50sbu', 'id': '4sTQVOfp9vEMCemLw50sbu',
			 'name': 'Galantis', 'type': 'artist', 'uri': 'spotify:artist:4sTQVOfp9vEMCemLw50sbu'}],
		          'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ',
		                                'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU',
		                                'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO',
		                                'PA', 'PY', 'PE', 'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR',
		                                'UY', 'US', 'GB', 'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA',
		                                'SA', 'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS',
		                                'IN', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR', 'BD',
		                                'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG', 'AG', 'AM', 'BS', 'BB', 'BZ', 'BT',
		                                'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT', 'JM',
		                                'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG',
		                                'PR', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL',
		                                'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM', 'GQ', 'SZ',
		                                'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ', 'ZW', 'BJ',
		                                'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE',
		                                'ET', 'XK'], 'disc_number': 1, 'duration_ms': 145807, 'explicit': False,
		          'external_ids': {'isrc': 'SEAMA2200001'},
		          'external_urls': {'spotify': 'https://open.spotify.com/track/5L5JUSGOaH6lulTUltJfgE'},
		          'href': 'https://api.spotify.com/v1/tracks/5L5JUSGOaH6lulTUltJfgE', 'id': '5L5JUSGOaH6lulTUltJfgE',
		          'is_local': False, 'name': 'Fading Like A Flower', 'popularity': 41,
		          'preview_url': 'https://p.scdn.co/mp3-preview/af7eae1634028106dabdd5e715307797f20a0c65?cid=2c9062fc93e94058be23890e28264258',
		          'track_number': 1, 'type': 'track', 'uri': 'spotify:track:5L5JUSGOaH6lulTUltJfgE'}, {
		          'album': {'album_type': 'single', 'artists': [
			          {'external_urls': {'spotify': 'https://open.spotify.com/artist/3gg8Dn97Im6uNAdafETuNp'},
			           'href': 'https://api.spotify.com/v1/artists/3gg8Dn97Im6uNAdafETuNp',
			           'id': '3gg8Dn97Im6uNAdafETuNp', 'name': 'Dancing DJs', 'type': 'artist',
			           'uri': 'spotify:artist:3gg8Dn97Im6uNAdafETuNp'}],
		                    'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR',
		                                          'CY', 'CZ', 'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR',
		                                          'GT', 'HN', 'HK', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY',
		                                          'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE', 'PH', 'PL',
		                                          'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB',
		                                          'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA',
		                                          'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO',
		                                          'PS', 'IN', 'BY', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK',
		                                          'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG',
		                                          'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM',
		                                          'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR',
		                                          'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG', 'WS',
		                                          'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL',
		                                          'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM',
		                                          'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW',
		                                          'TG', 'UZ', 'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM',
		                                          'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE', 'ET', 'XK'],
		                    'external_urls': {'spotify': 'https://open.spotify.com/album/7mI2SHSqYsRcqbfGeCvL7V'},
		                    'href': 'https://api.spotify.com/v1/albums/7mI2SHSqYsRcqbfGeCvL7V',
		                    'id': '7mI2SHSqYsRcqbfGeCvL7V', 'images': [
				          {'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2737d0f9dee9f561f2eb28af0b1',
				           'width': 640},
				          {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e027d0f9dee9f561f2eb28af0b1',
				           'width': 300},
				          {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048517d0f9dee9f561f2eb28af0b1',
				           'width': 64}], 'name': 'Fading Like A Flower', 'release_date': '2006-03-27',
		                    'release_date_precision': 'day', 'total_tracks': 1, 'type': 'album',
		                    'uri': 'spotify:album:7mI2SHSqYsRcqbfGeCvL7V'}, 'artists': [
			{'external_urls': {'spotify': 'https://open.spotify.com/artist/3gg8Dn97Im6uNAdafETuNp'},
			 'href': 'https://api.spotify.com/v1/artists/3gg8Dn97Im6uNAdafETuNp', 'id': '3gg8Dn97Im6uNAdafETuNp',
			 'name': 'Dancing DJs', 'type': 'artist', 'uri': 'spotify:artist:3gg8Dn97Im6uNAdafETuNp'}],
		          'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ',
		                                'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU',
		                                'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO',
		                                'PA', 'PY', 'PE', 'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR',
		                                'UY', 'US', 'GB', 'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA',
		                                'SA', 'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS',
		                                'IN', 'BY', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR',
		                                'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG', 'AG', 'AM', 'BS', 'BB', 'BZ',
		                                'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT',
		                                'JM', 'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW',
		                                'PG', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR', 'TL',
		                                'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM', 'GQ', 'SZ',
		                                'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ', 'ZW', 'BJ',
		                                'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE',
		                                'ET', 'XK'], 'disc_number': 1, 'duration_ms': 183281, 'explicit': False,
		          'external_ids': {'isrc': 'GBCFZ1700358'},
		          'external_urls': {'spotify': 'https://open.spotify.com/track/7lKnvy6Sy2HRVArVhgUAWR'},
		          'href': 'https://api.spotify.com/v1/tracks/7lKnvy6Sy2HRVArVhgUAWR', 'id': '7lKnvy6Sy2HRVArVhgUAWR',
		          'is_local': False, 'name': 'Fading Like A Flower', 'popularity': 44, 'preview_url': None,
		          'track_number': 1, 'type': 'track', 'uri': 'spotify:track:7lKnvy6Sy2HRVArVhgUAWR'}, {
		          'album': {'album_type': 'album', 'artists': [
			          {'external_urls': {'spotify': 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY'},
			           'href': 'https://api.spotify.com/v1/artists/2SHhfs4BiDxGQ3oxqf0UHY',
			           'id': '2SHhfs4BiDxGQ3oxqf0UHY', 'name': 'Roxette', 'type': 'artist',
			           'uri': 'spotify:artist:2SHhfs4BiDxGQ3oxqf0UHY'}],
		                    'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR',
		                                          'CY', 'CZ', 'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR',
		                                          'GT', 'HN', 'HK', 'HU', 'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY',
		                                          'MT', 'MX', 'NL', 'NZ', 'NI', 'NO', 'PA', 'PY', 'PE', 'PH', 'PL',
		                                          'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR', 'UY', 'US', 'GB',
		                                          'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA', 'SA',
		                                          'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO',
		                                          'PS', 'IN', 'BY', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK',
		                                          'RS', 'SI', 'KR', 'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG',
		                                          'AG', 'AM', 'BS', 'BB', 'BZ', 'BT', 'BW', 'BF', 'CV', 'CW', 'DM',
		                                          'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT', 'JM', 'KI', 'LS', 'LR',
		                                          'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW', 'PG', 'PR',
		                                          'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR',
		                                          'TL', 'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD',
		                                          'KM', 'GQ', 'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP',
		                                          'RW', 'TG', 'UZ', 'ZW', 'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ',
		                                          'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ', 'VE', 'ET', 'XK'],
		                    'external_urls': {'spotify': 'https://open.spotify.com/album/1pLZNTNM3IncoD6qVfO1rK'},
		                    'href': 'https://api.spotify.com/v1/albums/1pLZNTNM3IncoD6qVfO1rK',
		                    'id': '1pLZNTNM3IncoD6qVfO1rK', 'images': [
				          {'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273a1035156496a35002a9deeb5',
				           'width': 640},
				          {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02a1035156496a35002a9deeb5',
				           'width': 300},
				          {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851a1035156496a35002a9deeb5',
				           'width': 64}], 'name': 'Joyride 30th Anniversary Edition', 'release_date': '2021-11-26',
		                    'release_date_precision': 'day', 'total_tracks': 52, 'type': 'album',
		                    'uri': 'spotify:album:1pLZNTNM3IncoD6qVfO1rK'}, 'artists': [
			{'external_urls': {'spotify': 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY'},
			 'href': 'https://api.spotify.com/v1/artists/2SHhfs4BiDxGQ3oxqf0UHY', 'id': '2SHhfs4BiDxGQ3oxqf0UHY',
			 'name': 'Roxette', 'type': 'artist', 'uri': 'spotify:artist:2SHhfs4BiDxGQ3oxqf0UHY'}],
		          'available_markets': ['AR', 'AU', 'AT', 'BE', 'BO', 'BR', 'BG', 'CA', 'CL', 'CO', 'CR', 'CY', 'CZ',
		                                'DK', 'DO', 'DE', 'EC', 'EE', 'SV', 'FI', 'FR', 'GR', 'GT', 'HN', 'HK', 'HU',
		                                'IS', 'IE', 'IT', 'LV', 'LT', 'LU', 'MY', 'MT', 'MX', 'NL', 'NZ', 'NI', 'NO',
		                                'PA', 'PY', 'PE', 'PH', 'PL', 'PT', 'SG', 'SK', 'ES', 'SE', 'CH', 'TW', 'TR',
		                                'UY', 'US', 'GB', 'AD', 'LI', 'MC', 'ID', 'JP', 'TH', 'VN', 'RO', 'IL', 'ZA',
		                                'SA', 'AE', 'BH', 'QA', 'OM', 'KW', 'EG', 'MA', 'DZ', 'TN', 'LB', 'JO', 'PS',
		                                'IN', 'BY', 'KZ', 'MD', 'UA', 'AL', 'BA', 'HR', 'ME', 'MK', 'RS', 'SI', 'KR',
		                                'BD', 'PK', 'LK', 'GH', 'KE', 'NG', 'TZ', 'UG', 'AG', 'AM', 'BS', 'BB', 'BZ',
		                                'BT', 'BW', 'BF', 'CV', 'CW', 'DM', 'FJ', 'GM', 'GE', 'GD', 'GW', 'GY', 'HT',
		                                'JM', 'KI', 'LS', 'LR', 'MW', 'MV', 'ML', 'MH', 'FM', 'NA', 'NR', 'NE', 'PW',
		                                'PG', 'PR', 'WS', 'SM', 'ST', 'SN', 'SC', 'SL', 'SB', 'KN', 'LC', 'VC', 'SR',
		                                'TL', 'TO', 'TT', 'TV', 'VU', 'AZ', 'BN', 'BI', 'KH', 'CM', 'TD', 'KM', 'GQ',
		                                'SZ', 'GA', 'GN', 'KG', 'LA', 'MO', 'MR', 'MN', 'NP', 'RW', 'TG', 'UZ', 'ZW',
		                                'BJ', 'MG', 'MU', 'MZ', 'AO', 'CI', 'DJ', 'ZM', 'CD', 'CG', 'IQ', 'LY', 'TJ',
		                                'VE', 'ET', 'XK'], 'disc_number': 1, 'duration_ms': 235533, 'explicit': False,
		          'external_ids': {'isrc': 'SEAMA0900115'},
		          'external_urls': {'spotify': 'https://open.spotify.com/track/3IdUmJQH52iGzKxHmbitMX'},
		          'href': 'https://api.spotify.com/v1/tracks/3IdUmJQH52iGzKxHmbitMX', 'id': '3IdUmJQH52iGzKxHmbitMX',
		          'is_local': False, 'name': 'Fading Like a Flower (Every Time You Leave) - Humberto Gatica Mix',
		          'popularity': 36,
		          'preview_url': 'https://p.scdn.co/mp3-preview/79c5b67347d4bc300cc294f05a479bc38f7d9597?cid=2c9062fc93e94058be23890e28264258',
		          'track_number': 18, 'type': 'track', 'uri': 'spotify:track:3IdUmJQH52iGzKxHmbitMX'}, {
		          'album': {'album_type': 'compilation', 'artists': [
			          {'external_urls': {'spotify': 'https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of'},
			           'href': 'https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of',
			           'id': '0LyfQWJT6nXafLPZqxe9Of', 'name': 'Various Artists', 'type': 'artist',
			           'uri': 'spotify:artist:0LyfQWJT6nXafLPZqxe9Of'}], 'available_markets': ['GB', 'IE'],
		                    'external_urls': {'spotify': 'https://open.spotify.com/album/1UYxuXLWarmNNtHMAtg4G0'},
		                    'href': 'https://api.spotify.com/v1/albums/1UYxuXLWarmNNtHMAtg4G0',
		                    'id': '1UYxuXLWarmNNtHMAtg4G0', 'images': [
				          {'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2736879889cce7efb8652002e2e',
				           'width': 640},
				          {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e026879889cce7efb8652002e2e',
				           'width': 300},
				          {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048516879889cce7efb8652002e2e',
				           'width': 64}], 'name': 'Ultimate NRG Megamix', 'release_date': '2009-01-01',
		                    'release_date_precision': 'day', 'total_tracks': 90, 'type': 'album',
		                    'uri': 'spotify:album:1UYxuXLWarmNNtHMAtg4G0'}, 'artists': [
			{'external_urls': {'spotify': 'https://open.spotify.com/artist/3gg8Dn97Im6uNAdafETuNp'},
			 'href': 'https://api.spotify.com/v1/artists/3gg8Dn97Im6uNAdafETuNp', 'id': '3gg8Dn97Im6uNAdafETuNp',
			 'name': 'Dancing DJs', 'type': 'artist', 'uri': 'spotify:artist:3gg8Dn97Im6uNAdafETuNp'}],
		          'available_markets': ['GB', 'IE'], 'disc_number': 2, 'duration_ms': 66693, 'explicit': False,
		          'external_ids': {'isrc': 'GBCFZ0900868'},
		          'external_urls': {'spotify': 'https://open.spotify.com/track/2xtTd3RQod1RvDwchPB5vl'},
		          'href': 'https://api.spotify.com/v1/tracks/2xtTd3RQod1RvDwchPB5vl', 'id': '2xtTd3RQod1RvDwchPB5vl',
		          'is_local': False, 'name': 'Fading Like A Flower - Alex K Remix', 'popularity': 35,
		          'preview_url': None, 'track_number': 9, 'type': 'track',
		          'uri': 'spotify:track:2xtTd3RQod1RvDwchPB5vl'}], 'limit': 10,
	'next': 'https://api.spotify.com/v1/search?query=Fading+Like+A+Flower+%28Every+Time+You+Leave%29&type=track&offset=10&limit=10',
	'offset': 0, 'previous': None, 'total': 841}}

print(var['tracks']['items'][0]['uri'])
